#!/bin/zsh

# needed to use pdflatex to directly print latex tables or other text
# from tools.
# creates a new pdf file with a small border

if [ `which pdflatex` ] && [ $1 ]
then

    outfile=${1:r}
    
    tmpfile=/tmp/$(date +%s%N)
    trap "rm -rf $tmpfile; exit" SIGHUP SIGINT SIGTERM
    
    export TEXINPUTS=$CMSSW_BASE/src/WbWbXAnalysis/Tools/scripts/tex_packages:$TEXINPUTS
    
    printf "\\\documentclass[11pt]{article}">>| $tmpfile
#printf "\\\usepackage{blindtext}">>| $tmpfile
    printf "\\\usepackage[active,tightpage]{preview}">>| $tmpfile
     printf "\\\usepackage{multirow}">>| $tmpfile
    printf "\\\usepackage{more-ptdr-definitions}">>| $tmpfile

    printf "\\\setlength\\\PreviewBorder{10pt}" >>| $tmpfile
    printf "\\\usepackage[utf8]{inputenc} \\\usepackage{amsmath} \\\usepackage{amsfonts} \\\usepackage{amssymb} \\\usepackage{lmodern} \\\usepackage[T1]{fontenc} \\\usepackage{textcomp} \\\usepackage{underscore}  \\\usepackage{pdflscape}" >>| $tmpfile
    
    printf "\\\begin{document}\\\begin{preview}" >>| $tmpfile

    cat $1 >> $tmpfile
    
    printf "\\\end{preview}\\\end{document}"  >>| $tmpfile
    pdflatex -jobname=$outfile $tmpfile
    pdftopng $outfile.pdf $outfile
    mv $outfile-000001.png $outfile.png
    rm $tmpfile
    rm $outfile.aux
    rm $outfile.log

else
    echo "no pdflatex found" >>| $1.log
fi
