/********************************************************************
* TUnfoldV17Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TUnfoldV17Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTUnfoldV17Dict();
extern void G__cpp_setup_inheritanceTUnfoldV17Dict();
extern void G__cpp_setup_typetableTUnfoldV17Dict();
extern void G__cpp_setup_memvarTUnfoldV17Dict();
extern void G__cpp_setup_globalTUnfoldV17Dict();
extern void G__cpp_setup_memfuncTUnfoldV17Dict();
extern void G__cpp_setup_funcTUnfoldV17Dict();
extern void G__set_cpp_environmentTUnfoldV17Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TUnfoldV17.cxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TUnfoldV17DictLN_TClass;
extern G__linked_taginfo G__TUnfoldV17DictLN_TBuffer;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMemberInspector;
extern G__linked_taginfo G__TUnfoldV17DictLN_TObject;
extern G__linked_taginfo G__TUnfoldV17DictLN_TString;
extern G__linked_taginfo G__TUnfoldV17DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TUnfoldV17DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TUnfoldV17DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TUnfoldV17DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TArrayD;
extern G__linked_taginfo G__TUnfoldV17DictLN_TArrayI;
extern G__linked_taginfo G__TUnfoldV17DictLN_TH1;
extern G__linked_taginfo G__TUnfoldV17DictLN_TH2;
extern G__linked_taginfo G__TUnfoldV17DictLN_TSpline;
extern G__linked_taginfo G__TUnfoldV17DictLN_TGraph;
extern G__linked_taginfo G__TUnfoldV17DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TUnfoldV17DictLN_TUnfoldV17;
extern G__linked_taginfo G__TUnfoldV17DictLN_TUnfoldV17cLcLEConstraint;
extern G__linked_taginfo G__TUnfoldV17DictLN_TUnfoldV17cLcLERegMode;
extern G__linked_taginfo G__TUnfoldV17DictLN_TUnfoldV17cLcLEHistMap;

/* STUB derived class for protected member access */
