/********************************************************************
* TUnfoldBinningXMLV17Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TUnfoldBinningXMLV17Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTUnfoldBinningXMLV17Dict();
extern void G__cpp_setup_inheritanceTUnfoldBinningXMLV17Dict();
extern void G__cpp_setup_typetableTUnfoldBinningXMLV17Dict();
extern void G__cpp_setup_memvarTUnfoldBinningXMLV17Dict();
extern void G__cpp_setup_globalTUnfoldBinningXMLV17Dict();
extern void G__cpp_setup_memfuncTUnfoldBinningXMLV17Dict();
extern void G__cpp_setup_funcTUnfoldBinningXMLV17Dict();
extern void G__set_cpp_environmentTUnfoldBinningXMLV17Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TUnfoldBinningXMLV17.cxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TClass;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TBuffer;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMemberInspector;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TObject;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TNamed;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TUnfoldBinningV17;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TXMLNode;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TXMLDocument;
extern G__linked_taginfo G__TUnfoldBinningXMLV17DictLN_TUnfoldBinningXMLV17;

/* STUB derived class for protected member access */
