/********************************************************************
* TUnfoldSysV17Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TUnfoldSysV17Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTUnfoldSysV17Dict();
extern void G__cpp_setup_inheritanceTUnfoldSysV17Dict();
extern void G__cpp_setup_typetableTUnfoldSysV17Dict();
extern void G__cpp_setup_memvarTUnfoldSysV17Dict();
extern void G__cpp_setup_globalTUnfoldSysV17Dict();
extern void G__cpp_setup_memfuncTUnfoldSysV17Dict();
extern void G__cpp_setup_funcTUnfoldSysV17Dict();
extern void G__set_cpp_environmentTUnfoldSysV17Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TUnfoldSysV17.cxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TUnfoldSysV17DictLN_TClass;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TBuffer;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMemberInspector;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TObject;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMap;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TH1;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TH2;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TUnfoldV17;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TUnfoldV17cLcLEConstraint;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TUnfoldV17cLcLERegMode;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TUnfoldV17cLcLEHistMap;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TUnfoldSysV17;
extern G__linked_taginfo G__TUnfoldSysV17DictLN_TUnfoldSysV17cLcLESysErrMode;

/* STUB derived class for protected member access */
