/********************************************************************
* TUnfoldDensityV17Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TUnfoldDensityV17Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTUnfoldDensityV17Dict();
extern void G__cpp_setup_inheritanceTUnfoldDensityV17Dict();
extern void G__cpp_setup_typetableTUnfoldDensityV17Dict();
extern void G__cpp_setup_memvarTUnfoldDensityV17Dict();
extern void G__cpp_setup_globalTUnfoldDensityV17Dict();
extern void G__cpp_setup_memfuncTUnfoldDensityV17Dict();
extern void G__cpp_setup_funcTUnfoldDensityV17Dict();
extern void G__set_cpp_environmentTUnfoldDensityV17Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TUnfoldDensityV17.cxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TClass;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TBuffer;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMemberInspector;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TObject;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TString;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TH1;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TH2;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TSpline;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TGraph;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TUnfoldV17;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TUnfoldV17cLcLEConstraint;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TUnfoldV17cLcLERegMode;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TUnfoldV17cLcLEHistMap;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TUnfoldSysV17;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TUnfoldBinningV17;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TUnfoldDensityV17;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TUnfoldDensityV17cLcLEDensityMode;
extern G__linked_taginfo G__TUnfoldDensityV17DictLN_TUnfoldDensityV17cLcLEScanTauMode;

/* STUB derived class for protected member access */
